apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ${name}
  namespace: ${k8s_namespace}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: external-dns
      release: ${name}
